### ISSUE TITLE
Request: autowsmb level 4 skillchain

### ISSUE THREAD

**Issue by Heretic6667** [dabidobido/FFXIAddons#2]
Hi there, hope I'm wording this request correctly and it makes sense.

Looking to perform a 3-step double darkness skillchain while mutliboxing 3 characters who I want to skillchain in this order:

BRD > Mordant Rime
COR > Leaden Salute
COR > Wildfire

Is there a way to limit the 2nd cor into only attempting to skillchain when its at the 3rd step?  How its setup now both CORs are attempting to skillchain with the BRD.  Seems that the setsclevel variable only goes up to 3- I imagine if this could be increased to 4 it would solve my dilemma.  

If there is a better way of doing this that I haven't noticed, let me know :)

Thanks!

**Comment by dabidobido** [comment]
setsclvl now goes up to 4 in 1.3.1. I haven't tested it since I don't have time to set something up, but it should work in theory
