### ISSUE TITLE
autowsmb not bursting 

### ISSUE THREAD

**Issue by Heretic6667** [dabidobido/FFXIAddons#3]
I seem to be having difficulties getting one of my multi-box characters to magic burst off of a darkness skillchain.  

BRD > Mordant Rime
COR > Leaden Salute
= Darkness

BLM's "//awsmb status" returns:

      Don't open: false
      SC level: 2
      Spamming: false
      Fast Cast: 80
      Spell Priority 1: Blizzard VI (0% HP)

BLM's "//awsmb start mb" returns:

      Spell Priority 1: Blizzard VI (0% HP)
      Start MB: true

Is there something else I need to enter to get the BLM character to burst?  Does the BLM have to participate in the skillchaining to fire off a burst :( ?

Thanks again!

**Comment by dabidobido** [comment]
BLM needs to target the mob.
